[project]
name = "mylib"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "kojo-fan-art>=0.1.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
